#ifndef PARAMETROS_AG_H_INCLUDED
#define PARAMETROS_AG_H_INCLUDED

#define NUMERO_DE_GERACOES 100
#define DIMENSOES_PROBLEMA 30
#define TAMANHO_VALOR 7
#define TAMANHO_INDIVIDUO DIMENSOES_PROBLEMA*TAMANHO_VALOR
#define TAMANHO_POPULACAO 100
#define CRITERIO_DE_PARADA  n >= NUMERO_DE_GERACOES
#define TAXA_DE_MUTACAO 0.1
#define TAXA_DE_RECOMBINACAO 0.7

#define FUNCAO_DE_AVALIACAO(x) (x*x)

#endif // PARAMETROS_AG_H_INCLUDED
