#ifndef PARAMETROS_AG_H_INCLUDED
#define PARAMETROS_AG_H_INCLUDED

#define NUMERO_DE_GERACOES 100
#define TAMANHO_INDIVIDUO 7
#define TAMANHO_POPULACAO 100
#define CRITERIO_DE_PARADA  n > NUMERO_DE_GERACOES
#define TAXA_DE_MUTACAO 0.1
#define TAXA_DE_RECOMBINACAO 0.7

#endif // PARAMETROS_AG_H_INCLUDED
