#ifndef PARAMETROS_AG_H_INCLUDED
#define PARAMETROS_AG_H_INCLUDED

#define NUMERO_DE_GERACOES 1000
#define DIMENSOES_PROBLEMA 30
#define TAMANHO_VALOR 10
#define TAMANHO_INDIVIDUO DIMENSOES_PROBLEMA*TAMANHO_VALOR
#define TAMANHO_POPULACAO 100
#define CRITERIO_DE_PARADA  n >= NUMERO_DE_GERACOES
#define TAXA_DE_MUTACAO 0.001
#define TAXA_DE_RECOMBINACAO 0.7
#define TAMANHO_TORNEIO 5

#define ELITE 1

#endif // PARAMETROS_AG_H_INCLUDED
